name: Publish NuGet Package

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set VERSION from release tag
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Update <Version> in csproj
      run: |
        sed -i 's|<Version>.*</Version>|<Version>'$VERSION'</Version>|' src/Blazinga/Blazinga.csproj
        
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
            8.0.x
            9.0.x

    - name: Restore dependencies
      run: dotnet restore src/Blazinga/Blazinga.csproj

    - name: Build
      run: dotnet build src/Blazinga/Blazinga.csproj -c Release --no-restore
      
    - name: Strip 'v' prefix from version
      run: echo "PACKAGE_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

    - name: Pack NuGet package
      run: dotnet pack src/Blazinga/Blazinga.csproj -c Release -p:PackageVersion=${PACKAGE_VERSION} -o ./nupkgs

    - name: Publish NuGet package
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
